# Generated by Django 5.0.7 on 2024-09-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='status',
            field=models.CharField(blank=True, choices=[('opened', 'Opened'), ('closed', 'Closed')], default='opened', max_length=10),
        ),
    ]
