# Generated by Django 5.0.7 on 2024-10-02 19:54

import applications.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0002_jobpost_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('resume', models.FileField(upload_to=applications.models.upload_resume, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.pdf', '.doc', '.docx']), applications.models.validate_resume_file_extension])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('selected', 'selected'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('applicant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job_post', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='posts.jobpost')),
            ],
            options={
                'ordering': ['-created'],
                'unique_together': {('job_post', 'applicant')},
            },
        ),
    ]
