# Generated by Django 5.0.7 on 2024-10-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('selected', 'selected'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
