# Generated by Django 5.0.7 on 2024-08-26 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_city_created_city_updated_country_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='created',
        ),
        migrations.RemoveField(
            model_name='city',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='country',
            name='created',
        ),
        migrations.RemoveField(
            model_name='country',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='created',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='industry',
            name='created',
        ),
        migrations.RemoveField(
            model_name='industry',
            name='updated',
        ),
    ]
