# Generated by Django 5.0.7 on 2024-09-07 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_city_created_remove_city_updated_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
