# Generated by Django 5.0.7 on 2024-08-26 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_publisher',
            new_name='is_company',
        ),
    ]
